version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  ml-server:
    build: .
    container_name: crypto-predictor-server
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=*
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
