"""Add CANCELLED status to training sessions

Revision ID: 72929bfc7fb1
Revises: 0da951318e3b
Create Date: 2025-08-31 15:12:25.931660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '72929bfc7fb1'
down_revision = '0da951318e3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only change the session_id length, keep everything else as is
    op.alter_column('training_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_sessions', 'session_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
