"""Initial database schema

Revision ID: fac13219ec01
Revises: 
Create Date: 2025-08-31 14:55:24.027265

"""
from alembic import op
import sqlalchemy as sa


revision = 'fac13219ec01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('hidden_layers', sa.JSON(), nullable=True),
    sa.Column('dropout_rate', sa.Float(), nullable=True),
    sa.Column('activation_function', sa.String(length=50), nullable=True),
    sa.Column('optimizer', sa.String(length=50), nullable=True),
    sa.Column('loss_function', sa.String(length=50), nullable=True),
    sa.Column('validation_split', sa.Float(), nullable=True),
    sa.Column('early_stopping_patience', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configurations_config_hash'), 'model_configurations', ['config_hash'], unique=True)
    op.create_index(op.f('ix_model_configurations_is_active'), 'model_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_configurations_model_type'), 'model_configurations', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_configurations_ticker'), 'model_configurations', ['ticker'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='trainingstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('model_file_path', sa.String(length=255), nullable=True),
    sa.Column('training_logs', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_session_id'), 'training_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_training_sessions_ticker'), 'training_sessions', ['ticker'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('training_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_prediction_date'), 'predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_predictions_request_id'), 'predictions', ['request_id'], unique=True)
    op.create_index(op.f('ix_predictions_ticker'), 'predictions', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_ticker'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_request_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_date'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_training_sessions_ticker'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_session_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_model_configurations_ticker'), table_name='model_configurations')
    op.drop_index(op.f('ix_model_configurations_model_type'), table_name='model_configurations')
    op.drop_index(op.f('ix_model_configurations_is_active'), table_name='model_configurations')
    op.drop_index(op.f('ix_model_configurations_config_hash'), table_name='model_configurations')
    op.drop_table('model_configurations')
    # ### end Alembic commands ###
